apiVersion: apps/v1
kind: Deployment
metadata:
  name: qr-frontend
  namespace: qr
spec:
  revisionHistoryLimit: 2
  replicas: 1
  selector:
    matchLabels:
      app: qr-frontend
  template:
    metadata:
      labels:
        app: qr-frontend
    spec:
      containers:
        - name: qr-frontend
          image: ghcr.io/blainmac333/qr-frontend:3c74950d3418b578294c45ee6bafaa0ce6d941da
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_API_BASE
              value: /api
          resources:
            requests:
              cpu: "75m"
              memory: "160Mi"
            limits:
              cpu: "400m"
              memory: "320Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: qr-frontend
  namespace: qr
spec:
  selector:
    app: qr-frontend
  ports:
    - port: 3000
      targetPort: 3000