apiVersion: apps/v1
kind: Deployment
metadata:
  name: qr-frontend
  namespace: qr
spec:
  revisionHistoryLimit: 2
  replicas: 1
  selector:
    matchLabels:
      app: qr-frontend
  template:
    metadata:
      labels:
        app: qr-frontend
    spec:
      containers:
        - name: qr-frontend
          image: ghcr.io/blainmac333/qr-frontend:2c50cd24168de498e09877837f7a041b724af798
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_API_BASE
              value: /api
          resources:
            requests:
              cpu: "75m"
              memory: "160Mi"
            limits:
              cpu: "400m"
              memory: "320Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: qr-frontend
  namespace: qr
spec:
  selector:
    app: qr-frontend
  ports:
    - port: 3000
      targetPort: 3000