# velero/metrics-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: velero-metrics
  namespace: velero
spec:
  selector:
    name: velero
  ports:
    - name: http-metrics
      port: 8085
      targetPort: 8085
---
apiVersion: v1
kind: Service
metadata:
  name: velero-metrics-nodeport
  namespace: velero
spec:
  type: NodePort
  selector:
    name: velero
  ports:
    - name: http-metrics
      port: 8085
      targetPort: 8085
      nodePort: 31085