apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qr-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Blainmac333/Devops-Project.git
    targetRevision: master
    path: k8s
  destination:
    name: in-cluster          
    namespace: qr
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true