name: Build and Test

on:
  pull_request:
    branches:
      - master
  push:
    branches-ignore:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          cd api
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push API Docker image
        uses: docker/build-push-action@v7
        with:
          context: ./api
          file: ./api/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/qr-code-api:${{ github.sha }}

      - name: Build and push Frontend Docker image
        uses: docker/build-push-action@v7
        with:
          context: ./front-end-nextjs
          file: ./front-end-nextjs/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/qr-code-frontend:${{ github.sha }}
